"use strict";
let first = 12.0;
let second = 0x37CF;
let third = 0o377;
let fourth = 0b111001;
console.log("Number Data Type Demo");
console.log("------------------");
console.log(first);
console.log(second);
console.log(third);
console.log(fourth);
